export enum ErrorCodes {
  ERRO_INESPERADO = 1000,
  CADASTRO_NAO_PODE_SER_REALIZADO,
  CAMPO_OBRIGATORIO,
  PARAMETRO_INVALIDO,
  TOKEN_INVALIDO,
  DADO_NAO_ENCONTRADO,
  DADO_CONFLITANTE,
  DADO_INCONSISTENTE,
  DADO_NAO_PODE_SER_REMOVIDO,
  DADO_NAO_PODE_SER_ATUALIZADO,
  ATUALIZACAO_NAO_PODE_SER_REALIZADA,
}
